#!/bin/bash

env

. /usr/share/mkapp/functions

if [ "$PACKAGING" ]; then  
  rewrite
  build -F

  if [ "$PUBLISH" ]; then
    publish_debs
  fi
fi

if [ "$IMAGING" ]; then
  init
  update
  assume lsb-base all 10
  assume adduser all 3.10
  setup mosquitto mqtt
  cat >> Dockerfile <<EOF          
EXPOSE 1883
EXPOSE 8883
EXPOSE 9001
EOF
  finish '/opt/menucha-de' '["/opt/menucha-de/mqtt", "-p", "80"]'
  cat Dockerfile
fi





